use_frameworks!

target 'TPCoreUtils_Example' do
  pod 'TPCoreUtils', :path => '../'

  target 'TPCoreUtils_Tests' do
    inherit! :search_paths
    pod 'TPCoreUtils', :path => '../'
    pod 'Nimble', '~> 7.0.2'
  end
end
